// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240412025327_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("API.Models.Cat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("acessos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("idade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("peso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("src")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("total_comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            id = 1,
                            acessos = "209293",
                            author = "Ashley",
                            date = "2024-03-20 21:16:20",
                            idade = "2",
                            peso = "5",
                            src = "https://i.pinimg.com/564x/e7/54/cc/e754cc4c1e43e85ae059d640ac3a4d81.jpg",
                            title = "Fifi",
                            total_comments = "2"
                        },
                        new
                        {
                            id = 2,
                            acessos = "123345",
                            author = "Mat",
                            date = "2024-04-10 21:16:20",
                            idade = "6",
                            peso = "6",
                            src = "https://i.pinimg.com/564x/6c/93/e6/6c93e605661e7d105bd6ad473ccfaa45.jpg",
                            title = "Mingau",
                            total_comments = "1"
                        },
                        new
                        {
                            id = 3,
                            acessos = "13215",
                            author = "João",
                            date = "2024-02-02 21:16:20",
                            idade = "3",
                            peso = "3",
                            src = "https://i.pinimg.com/564x/01/e6/09/01e6097603ceb0a1c3b16af1a8f56f39.jpg",
                            title = "Bolinho",
                            total_comments = "1"
                        },
                        new
                        {
                            id = 4,
                            acessos = "56746",
                            author = "Ana",
                            date = "2024-01-12 21:16:20",
                            idade = "8",
                            peso = "2",
                            src = "https://i.pinimg.com/564x/01/88/b4/0188b44239015be9f8efe7e81aa3d40a.jpg",
                            title = "Nico",
                            total_comments = "0"
                        },
                        new
                        {
                            id = 5,
                            acessos = "76",
                            author = "Ricardo",
                            date = "2024-03-21 21:16:20",
                            idade = "1",
                            peso = "4",
                            src = "https://i.pinimg.com/564x/ef/10/c2/ef10c2acca595eae0b0f67430580c3a1.jpg",
                            title = "Maggie",
                            total_comments = "0"
                        },
                        new
                        {
                            id = 6,
                            acessos = "365753",
                            author = "Mat",
                            date = "2024-04-14 21:16:20",
                            idade = "9",
                            peso = "4",
                            src = "https://i.pinimg.com/564x/92/73/c6/9273c692dd46fbb5b3d9b5018e09ee61.jpg",
                            title = "Tom",
                            total_comments = "0"
                        });
                });

            modelBuilder.Entity("API.Models.Phone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("38987d73-054f-4236-937c-3c105a09a9f9"),
                            Birthday = "01/01/1900",
                            CPF = "123.123.123-45",
                            IsActive = true,
                            Name = "Mat",
                            Password = "admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("API.Models.Phone", b =>
                {
                    b.HasOne("API.Models.User", "User")
                        .WithMany("Phones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
